apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: intern-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: registry
    spec:
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: registry
        image: 10.1.0.4:5000/repository/value/infra-amine-intern/registry:latest1
        imagePullPolicy:  IfNotPresent
        ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        resources:
            requests:
              cpu: 400m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 1000Mi
        livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
              scheme: HTTP
            initialDelaySeconds: 90
            failureThreshold: 3
            periodSeconds: 15
            timeoutSeconds: 5
          
        readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
              scheme: HTTP
            initialDelaySeconds: 90
            failureThreshold: 3
            periodSeconds: 15
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: intern-deploy
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry-cluster-ip
  namespace: intern-deploy
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
