#!/usr/bin/env groovy
@Library('jenkins-shared-library')
def gv

pipeline {
  
  agent any
  tools {
        jdk "java-11"
    }
  stages {
    stage("init") {
      steps {
         script {
           gv = load "script.groovy"
         }
       }
     }
    stage("build jar") {
      
      steps {
        script {
          buildJar()    
      }
    }
  }   
 }
}
