apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: intern-deploy
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: intern-deploy
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:12.0.3
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        # db
        - name: DB_VENDOR
          value: "mysql"
        - name: DB_ADDR
          value: "mysql-valueds-002.mysql.database.azure.com"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "infra_keycloak"
        - name: JDBC_PARAMS
          value: "&useSSL=true&requireSSL=false&serverTimezone=UTC"
        - name: DB_USER
          value: "value@mysql-valueds-002"
        - name: DB_PASSWORD
          value: "Vds@2021"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
