apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: intern-deploy
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: intern-deploy
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: keycloak
          image: 10.1.0.4:5000/repository/value/infra-amine-intern/keycloak:latest
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
