server:
  port: 9915

## Registry
eureka:
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
    metadataMap:
      public: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8080}/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
#          type: ENV
#          value: SIG_SECRET_KEY
          type: VALUE
          value: JWTSecretKeyDontUseInProduction!

# Spring health monitoring
management:
  endpoints:
    jmx:
      domain: ${spring.application.name}
    web:
      exposure:
        include: prometheus, health, info, metrics
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      group:
        readiness:
          include: '*'
          show-details: when_authorized
        liveness:
          include: ping
          show-details: never
      show-details: when_authorized
      roles:
        - ADMIN
        - ROLE_ADMIN
        - ROLE_ACTUATOR

# Logging
logging:
  level:
    root: INFO
    com.value: DEBUG

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:access-manager;Mode=Oracle
    platform: h2
    continue-on-error: true
  jpa:
    generate-ddl: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yml